name: Test composer install

on:
  pull_request:
    branches:
      - *.x

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: 8.1
        extensions: Imagick, gd, pdo_mysql

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Start MySql service
      run: |
        sudo /etc/init.d/mysql start
        mysql -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"

    - name: Allow all plugins
      run: |
        composer config allow-plugins.cweagans/composer-patches true --no-plugins
        composer config allow-plugins.drupal/core-composer-scaffold true --no-plugins
        composer config allow-plugins.composer/installers true --no-plugins
        composer config allow-plugins.oomphinc/composer-installers-extender true --no-plugins
        composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true --no-plugins

    - name: Install dependencies
      run: composer install

    - name: Install Thunder
      run: vendor/bin/drush si thunder --db-url=mysql://root:root@127.0.0.1/testing -y
